-- CreateEnum
CREATE TYPE "University" AS ENUM ('AFRICAN_LEADERSHIP_UNIVERSITY', 'UNIVERSITY_OF_RWANDA', 'ADVENTIST_UNIVERSITY_OF_CENTRAL_AFRICA', 'INES_RUHENGERI', 'KIGALI_INDEPENDENT_UNIVERSITY', 'RWANDA_POLYTECHNIC', 'CARNEGIE_MELLON_UNIVERSITY_AFRICA', 'OTHER');

-- CreateTable
CREATE TABLE "User" (
    "id" TEXT NOT NULL,
    "email" TEXT NOT NULL,
    "password" TEXT NOT NULL,
    "fullName" TEXT NOT NULL,
    "university" "University" NOT NULL,
    "resetToken" TEXT,
    "resetTokenExpiry" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "User_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "User_email_key" ON "User"("email");
